### ISSUE TITLE
Change name of  saml-to.yaml

### ISSUE THREAD

**Issue by littlejo** [saml-to/assume-aws-role-action#4]
Hello,

is it possible to change filename in option?

Best regards,

**Comment by cnuss** [comment]
Hi @littlejo, not currently, but I can add this as a feature request. What would you like to change it to?

**Comment by cnuss** [comment]
@littlejo would you be able to reach out to me on Twitter, I'd love some feedback from you: https://twitter.com/chrisnuss or https://twitter.com/SamlToSupport

**Comment by cnuss** [comment]
@littlejo we've published a new release of this action which may suit your needs

you can now add `configPath:` to the `saml-to/assume-aws-role-action@v1` to indicate which config file to use.

for example:

```
      # uses saml-to.yml in the repository
      - uses: saml-to/assume-aws-role-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          role: "arn:aws:iam::123456789012:role/some-role"
      - uses: saml-to/assume-aws-role-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          role: "arn:aws:iam::123456789012:role/some-role"
          configPath: some-config-file.yml
```
